#!/bin/sh
#
# Subscribe feeds in akregator from firefox
#
# Original script by bcooksley
# https://forum.kde.org/viewtopic.php?f=18&t=111965
#

pidof 'akregator' || akregator --hide-mainwindow

for url; do
    url="${url#feed://}"
    url="${url#feed:}"      # For https links (feed:https://)

    qdbus org.kde.akregator /Akregator org.kde.akregator.part.addFeedsToGroup "$url" "Imported Feeds"
done

